language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.3
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --ignore=E128,E501 templated_email"
  - "pyflakes templated_email"
script:
  - python manage.py test
