language: python

python:
  - "3.6"

env:
  - TOX_ENV=py36-flake8
  - TOX_ENV=py34-django20
  - TOX_ENV=py35-django20
  - TOX_ENV=py36-django20
  - TOX_ENV=py37-django20
  - TOX_ENV=py35-django21
  - TOX_ENV=py36-django21
  - TOX_ENV=py37-django21
  - TOX_ENV=py35-django22
  - TOX_ENV=py36-django22
  - TOX_ENV=py37-django22
  - TOX_ENV=py38-django22
  - TOX_ENV=py36-django30
  - TOX_ENV=py37-django30
  - TOX_ENV=py38-django30

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_script:
  coveralls
